version: "3"
services:
  cephalocoin:
    build: ./
    image: cephalocoin
    environment:
      MNEMONIC: this is just some fake mnemonic used instead of a real one
      INFURA_PROJECT_ID: aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa
    working_dir: /usr/src/app
    volumes:
      - ./:/usr/src/app
      - exclude:/usr/src/app/node_modules/
    ports:
      - 8545:8545
    command: ganache-cli --account_keys_path ./keys.json

volumes:
  exclude:
