version: "3"
services:
  cephalocoin:
    build: ./
    image: cephalocoin
    working_dir: /usr/src/app
    volumes:
      - ./:/usr/src/app
      - exclude:/usr/src/app/node_modules/
    ports:
      - 8545:8545
    command: ganache-cli --account_keys_path ./keys.json

volumes:
  exclude:
